version: '3.8'

services:
  api1:
    build:
      context: ./api1
      dockerfile: Dockerfile-auth
    ports:
      - "8080:8080"
    depends_on:
      - database

  api2:
    build:
      context: ./api2
      dockerfile: Dockerfile-catalog
    ports:
      - "8081:8081"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
